### ISSUE TITLE
Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got 

### ISSUE THREAD

**Issue by yousefis** [apple/ml-cvnets#40]
Hi,
I am getting the below error while am trying to train mobilevit for a custom dataset with 2 classes. 

` cvnets-train --common.config-file config/classification/imagenet/mobilevit_v1.yaml --common.results-loc classification_results
`
The dataset structure is as below:

train
   -class1
   -class2
validation
   -class1
   -class2

Any idea?

```
2022-07-20 17:02:33 - INFO    - Configuration file is stored here: classification_results/run_1/config.yaml
===========================================================================
2022-07-20 17:02:35 - DEBUG    - Training epoch 0 with 9873 samples
2022-07-20 17:02:49 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:49 - ERROR   - Exiting!!!
2022-07-20 17:02:49 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:49 - ERROR   - Exiting!!!
2022-07-20 17:02:49 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:49 - ERROR   - Exiting!!!
2022-07-20 17:02:50 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:50 - ERROR   - Exiting!!!
2022-07-20 17:02:50 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:50 - ERROR   - Exiting!!!
2022-07-20 17:02:52 - LOGS    - Exception occurred that interrupted the training. DataLoader worker (pid(s) 30836, 16400, 36564, 21248, 32388) exited unexpectedly
DataLoader worker (pid(s) 30836, 16400, 36564, 21248, 32388) exited unexpectedly
Traceback (most recent call last):
  File "d:\tools\mobile\lib\site-packages\torch\utils\data\dataloader.py", line 1134, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "D:\Tools\PVPython\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Sahar\ml-cvnets\engine\training_engine.py", line 682, in run
    train_loss, train_ckpt_metric = self.train_epoch(epoch)
  File "E:\Sahar\ml-cvnets\engine\training_engine.py", line 298, in train_epoch
    for batch_id, batch in enumerate(self.train_loader):
  File "d:\tools\mobile\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "d:\tools\mobile\lib\site-packages\torch\utils\data\dataloader.py", line 1330, in _next_data
    idx, data = self._get_data()
  File "d:\tools\mobile\lib\site-packages\torch\utils\data\dataloader.py", line 1296, in _get_data
    success, data = self._try_get_data()
  File "d:\tools\mobile\lib\site-packages\torch\utils\data\dataloader.py", line 1147, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 30836, 16400, 36564, 21248, 32388) exited unexpectedly
2022-07-20 17:02:52 - LOGS    - Training took 00:00:18.76
2022-07-20 17:02:52 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:52 - ERROR   - Exiting!!!
2022-07-20 17:02:52 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:52 - ERROR   - Exiting!!!
2022-07-20 17:02:54 - ERROR   - Unable to stack the tensors. Error: expected Tensor as element 0 in argument 0, but got numpy.int32
2022-07-20 17:02:54 - ERROR   - Exiting!!!
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\Tools\PVPython\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "D:\Tools\PVPython\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "D:\Tools\PVPython\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "D:\Tools\PVPython\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "D:\Tools\PVPython\lib\multiprocessing\connection.py", line 290, in _send_bytes
    nwritten, err = ov.GetOverlappedResult(True)
  File "D:\Tools\PVPython\lib\multiprocessing\connection.py", line 290, in _send_bytes
    nwritten, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended
BrokenPipeError: [WinError 109] The pipe has been endedv
```

**Comment by sacmehta** [comment]
It seems that collation is not happening properly for your dataset. You may refer to this [example code](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/data/datasets/classification/imagenet.py#L181) and implement a collate function for your dataset.

Notes: 

1. Do not forget to register it with a unique name.
2. Also, you can set collate function values to the new collate function as default in your dataset class (see [here](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/data/datasets/classification/imagenet.py#L53) for an example).

Hope this helps!!
